Repository furkandeveloper/EasyProfiler, pull requests merged in 2020-10, with the labels that each got.

#2 🔀 Implement db context
  src/QueryProfiler/Context/ProfilerDbContext.cs
  src/QueryProfiler/Context/ProfilerIdentityDbContext.cs
  src/QueryProfiler/QueryProfiler.csproj
Labels: enhancement, pull_request

#5 Feature/dbcontext configuration
  src/QueryProfiler/Context/ProfilerDbContext.cs
  src/QueryProfiler/Context/ProfilerDbContext{TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken}.cs
  src/QueryProfiler/Context/ProfilerDbContext{TUser,TRole,TKey}.cs
  src/QueryProfiler/Context/ProfilerDbContext{TUser}.cs
  src/QueryProfiler/Extensions/Interception.cs
  src/QueryProfiler/Extensions/ServiceCollection.cs
Labels: enhancement, good first issue, pull_request

#7 Feature/entities
  src/QueryProfiler/Context/ProfilerDbContext.cs
  src/QueryProfiler/Entities/BaseEntity.cs
  src/QueryProfiler/Entities/Profiler.cs
  src/QueryProfiler/Generators/GuidGenerator.cs
Labels: enhancement

#9 Feature/separate db
  EasyProfiler.sln
  src/EasyProfiler.Entities/BaseEntity.cs
  src/EasyProfiler.Entities/EasyProfiler.Entities.csproj
  src/EasyProfiler.Entities/GuidGenerator.cs
  src/EasyProfiler.Entities/Profiler.cs
  src/EasyProfiler.SQLServer/Context/DesignTimeDbContext.cs
  src/EasyProfiler.SQLServer/Context/ProfilerDbContext.cs
  src/EasyProfiler.SQLServer/EasyProfiler.SQLServer.csproj
  src/EasyProfiler.SQLServer/Extensions/ApplicationBuilder.cs
  src/EasyProfiler.SQLServer/Extensions/Interception.cs
  src/EasyProfiler.SQLServer/Extensions/ServiceCollection.cs
  src/EasyProfiler.SQLServer/Migrations/20201015185716_Initial.Designer.cs
  src/EasyProfiler.SQLServer/Migrations/20201015185716_Initial.cs
  src/EasyProfiler.SQLServer/Migrations/ProfilerDbContextModelSnapshot.cs
  src/QueryProfiler/Context/ProfilerDbContext{TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken}.cs
  src/QueryProfiler/Context/ProfilerDbContext{TUser,TRole,TKey}.cs
  src/QueryProfiler/Context/ProfilerDbContext{TUser}.cs
Labels: bug, enhancement

#14 🔀 Feature/advanced query
  EasyProfiler.sln
  src/EasyProfiler.Core/EasyProfiler.Core.csproj
  src/EasyProfiler.Core/Helpers/Attributes/ToLowerContainsComparisonAttribute.cs
  src/EasyProfiler.SQLServer/Abstractions/IEasyProfilerService.cs
  src/EasyProfiler.SQLServer/Concrete/EasyProfilerManager.cs
  src/EasyProfiler.SQLServer/EasyProfiler.SQLServer.csproj
  src/EasyProfiler.SQLServer/Models/AdvancedFilterModel.cs
Labels: enhancement

#16 Feature/swagger docs
  samples/EasyProfiler.Web/Controllers/DefaultController.cs
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/EasyProfiler.Web.xml
  samples/EasyProfiler.Web/Startup.cs
  samples/EasyProfiler.Web/appsettings.json
  src/EasyProfiler.SQLServer/Concrete/EasyProfilerManager.cs
  src/EasyProfiler.SQLServer/Interceptors/EasyProfilerInterceptors.cs
Labels: enhancement

#17 🔀 Feature/sample
  .gitignore
  EasyProfiler.sln
  samples/EasyProfiler.Web/Controllers/DefaultController.cs
  samples/EasyProfiler.Web/Customer.cs
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/EasyProfiler.Web.xml
  samples/EasyProfiler.Web/Migrations/20201019202625_Initial.Designer.cs
  samples/EasyProfiler.Web/Migrations/20201019202625_Initial.cs
  samples/EasyProfiler.Web/Migrations/SampleDbContextModelSnapshot.cs
  samples/EasyProfiler.Web/Program.cs
  samples/EasyProfiler.Web/Properties/launchSettings.json
  samples/EasyProfiler.Web/SampleDbContext.cs
  samples/EasyProfiler.Web/Startup.cs
  samples/EasyProfiler.Web/appsettings.json
  src/EasyProfiler.Core/EasyProfiler.Core.csproj
  src/EasyProfiler.Core/Helpers/Attributes/ToLowerContainsComparisonAttribute.cs
  src/EasyProfiler.SQLServer/Abstractions/IEasyProfilerService.cs
  src/EasyProfiler.SQLServer/Concrete/EasyProfilerManager.cs
  src/EasyProfiler.SQLServer/Context/ProfilerDbContext.cs
  src/EasyProfiler.SQLServer/EasyProfiler.SQLServer.csproj
  src/EasyProfiler.SQLServer/Extensions/ApplicationBuilder.cs
  src/EasyProfiler.SQLServer/Extensions/Interception.cs
  src/EasyProfiler.SQLServer/Migrations/20201021171356_Initial.Designer.cs
  src/EasyProfiler.SQLServer/Migrations/20201021171356_Initial.cs
  src/EasyProfiler.SQLServer/Migrations/20201021172101_ChangeDurationType.Designer.cs
  src/EasyProfiler.SQLServer/Migrations/20201021172101_ChangeDurationType.cs
  src/EasyProfiler.SQLServer/Migrations/ProfilerDbContextModelSnapshot.cs
  src/EasyProfiler.SQLServer/Models/AdvancedFilterModel.cs
Labels: enhancement, pull_request

#18 🔀 Feature/documentation
  samples/EasyProfiler.Web/Controllers/DefaultController.cs
  samples/EasyProfiler.Web/Docs/README.md
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
Labels: documentation

#21 🔀 Release/sql server
  samples/EasyProfiler.Web/Docs/README.md
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/Startup.cs
  src/EasyProfiler.Core/EasyProfiler.Core.csproj
  src/EasyProfiler.Core/easyProfilerSQLServer.png
  src/EasyProfiler.Entities/EasyProfiler.Entities.csproj
  src/EasyProfiler.Entities/easyProfilerSQLServer.png
  src/EasyProfiler.SQLServer/EasyProfiler.SQLServer.csproj
  src/EasyProfiler.SQLServer/easyProfilerSQLServer.png
Labels: enhancement, pull_request

#24 🔀 EasyProfiler.SQLServer
  .dockerignore
  .github/workflows/dotnet-core.yml
  Dockerfile
  EasyProfiler.sln
  README.md
  samples/EasyProfiler.Web/Docs/README.md
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/Properties/launchSettings.json
Labels: enhancement, pull_request

#25 Added EasyProfiler.MariaDb.
  src/EasyProfiler.MariaDb/Abstractions/IEasyProfilerService.cs
  src/EasyProfiler.MariaDb/Concrete/EasyProfilerManager.cs
  src/EasyProfiler.MariaDb/Context/DesignTimeDbContext.cs
  src/EasyProfiler.MariaDb/Context/ProfilerDbContext.cs
  src/EasyProfiler.MariaDb/EasyProfiler.MariaDb.csproj
  src/EasyProfiler.MariaDb/Extensions/ApplicationBuilder.cs
  src/EasyProfiler.MariaDb/Extensions/Interception.cs
  src/EasyProfiler.MariaDb/Extensions/ServiceCollection.cs
  src/EasyProfiler.MariaDb/Interceptors/EasyProfilerInterceptors.cs
  src/EasyProfiler.MariaDb/Migrations/20201025204520_Initial.Designer.cs
  src/EasyProfiler.MariaDb/Migrations/20201025204520_Initial.cs
  src/EasyProfiler.MariaDb/Migrations/ProfilerDbContextModelSnapshot.cs
  src/EasyProfiler.MariaDb/Models/AdvancedFilterModel.cs
  src/EasyProfiler.MariaDb/easyProfilerMariaDb.png
Labels: enhancement, pull_request

#28 🔀 🐛 Not working time for mariadb
  src/EasyProfiler.MariaDb/Context/ProfilerDbContext.cs
  src/EasyProfiler.MariaDb/Extensions/ApplicationBuilder.cs
  src/EasyProfiler.MariaDb/Extensions/Interception.cs
  src/EasyProfiler.MariaDb/Migrations/20201027202735_Initial.Designer.cs
  src/EasyProfiler.MariaDb/Migrations/20201027202735_Initial.cs
  src/EasyProfiler.MariaDb/Migrations/ProfilerDbContextModelSnapshot.cs
Labels: bug, invalid, pull_request

#31 🔀 Feature/common base service
  samples/EasyProfiler.Web/Controllers/DefaultController.cs
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/EasyProfiler.Web.xml
  samples/EasyProfiler.Web/Startup.cs
  src/EasyProfiler.Core/Abstractions/IEasyProfilerBaseService.cs
  src/EasyProfiler.Core/Concrete/EasyProfilerBaseManager.cs
  src/EasyProfiler.Core/EasyProfiler.Core.csproj
  src/EasyProfiler.Core/Helpers/AdvancedQuery/AdvancedFilterModel.cs
  src/EasyProfiler.MariaDb/Abstractions/IEasyProfilerService.cs
  src/EasyProfiler.MariaDb/Concrete/EasyProfilerManager.cs
  src/EasyProfiler.MariaDb/Extensions/Interception.cs
  src/EasyProfiler.MariaDb/Extensions/ServiceCollection.cs
  src/EasyProfiler.MariaDb/Interceptors/EasyProfilerInterceptors.cs
  src/EasyProfiler.SQLServer/Abstractions/IEasyProfilerService.cs
  src/EasyProfiler.SQLServer/Concrete/EasyProfilerManager.cs
  src/EasyProfiler.SQLServer/Extensions/ApplicationBuilder.cs
  src/EasyProfiler.SQLServer/Extensions/Interception.cs
  src/EasyProfiler.SQLServer/Extensions/ServiceCollection.cs
  src/EasyProfiler.SQLServer/Interceptors/EasyProfilerInterceptors.cs
  src/EasyProfiler.SQLServer/Models/AdvancedFilterModel.cs
Labels: pull_request, refactor

#32 ♻️ Refactor Service layer
  samples/EasyProfiler.Web/Controllers/DefaultController.cs
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/EasyProfiler.Web.xml
  samples/EasyProfiler.Web/Startup.cs
  src/EasyProfiler.Core/Abstractions/IEasyProfilerBaseService.cs
  src/EasyProfiler.Core/Concrete/EasyProfilerBaseManager.cs
  src/EasyProfiler.Core/EasyProfiler.Core.csproj
  src/EasyProfiler.Core/Helpers/AdvancedQuery/AdvancedFilterModel.cs
  src/EasyProfiler.MariaDb/Abstractions/IEasyProfilerService.cs
  src/EasyProfiler.MariaDb/Concrete/EasyProfilerManager.cs
  src/EasyProfiler.MariaDb/Extensions/Interception.cs
  src/EasyProfiler.MariaDb/Extensions/ServiceCollection.cs
  src/EasyProfiler.MariaDb/Interceptors/EasyProfilerInterceptors.cs
  src/EasyProfiler.SQLServer/Abstractions/IEasyProfilerService.cs
  src/EasyProfiler.SQLServer/Concrete/EasyProfilerManager.cs
  src/EasyProfiler.SQLServer/Extensions/ApplicationBuilder.cs
  src/EasyProfiler.SQLServer/Extensions/Interception.cs
  src/EasyProfiler.SQLServer/Extensions/ServiceCollection.cs
  src/EasyProfiler.SQLServer/Interceptors/EasyProfilerInterceptors.cs
  src/EasyProfiler.SQLServer/Models/AdvancedFilterModel.cs
Labels: pull_request, refactor
