Repository furkandeveloper/EasyProfiler, pull requests merged in 2020-11, with the labels that each got.

#34 🔀 Feature/postgre sql
  EasyProfiler.sln
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/Migrations/20201019202625_Initial.Designer.cs
  samples/EasyProfiler.Web/Migrations/20201019202625_Initial.cs
  samples/EasyProfiler.Web/Migrations/SampleDbContextModelSnapshot.cs
  src/EasyProfiler.PostgreSQL/Context/DesignTimeDbContext.cs
  src/EasyProfiler.PostgreSQL/Context/ProfilerDbContext.cs
  src/EasyProfiler.PostgreSQL/EasyProfiler.PostgreSQL.csproj
  src/EasyProfiler.PostgreSQL/Extensions/ApplicationBuilder.cs
  src/EasyProfiler.PostgreSQL/Extensions/Interception.cs
  src/EasyProfiler.PostgreSQL/Extensions/ServiceCollection.cs
  src/EasyProfiler.PostgreSQL/Interceptors/EasyProfilerInterceptors.cs
  src/EasyProfiler.PostgreSQL/Migrations/20201101113017_Initial.Designer.cs
  src/EasyProfiler.PostgreSQL/Migrations/20201101113017_Initial.cs
  src/EasyProfiler.PostgreSQL/Migrations/ProfilerDbContextModelSnapshot.cs
Labels: enhancement, pull_request

#36 🔀 Feature/sample
  heroku.yml
  samples/EasyProfiler.Web/Controllers/DefaultController.cs
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/EasyProfiler.Web.xml
  samples/EasyProfiler.Web/Migrations/20201101120654_Initial.Designer.cs
  samples/EasyProfiler.Web/Migrations/20201101120654_Initial.cs
  samples/EasyProfiler.Web/Migrations/SampleDbContextModelSnapshot.cs
  samples/EasyProfiler.Web/Startup.cs
Labels: enhancement, pull_request

#38 ♻ AutoFilterer.Swagger Implementation & tiny refactors
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/Startup.cs
Labels: documentation, enhancement

#39 Develop to master
  samples/EasyProfiler.Web/EasyProfiler.Web.csproj
  samples/EasyProfiler.Web/Startup.cs
Labels: documentation, enhancement

#40 Create LICENSE
  LICENSE
Labels: pull_request

#42 🔀 💥 Feature/change data type
  src/EasyProfiler.SQLServer/Context/ProfilerDbContext.cs
  src/EasyProfiler.SQLServer/Migrations/20201021171356_Initial.Designer.cs
  src/EasyProfiler.SQLServer/Migrations/20201021172101_ChangeDurationType.cs
  src/EasyProfiler.SQLServer/Migrations/20201107194601_ChangeDurationDataType.Designer.cs
  src/EasyProfiler.SQLServer/Migrations/20201107194601_ChangeDurationDataType.cs
  src/EasyProfiler.SQLServer/Migrations/ProfilerDbContextModelSnapshot.cs
Labels: Change Request, pull_request

#43 🚀 Deploy SQL Server provider.
  src/EasyProfiler.SQLServer/EasyProfiler.SQLServer.csproj
Labels: Change Request, documentation, pull_request

#52 🔀 Hotfix/request url
  src/EasyProfiler.MariaDb/EasyProfiler.MariaDb.csproj
  src/EasyProfiler.MariaDb/Extensions/Interception.cs
  src/EasyProfiler.MariaDb/Interceptors/EasyProfilerInterceptors.cs
  src/EasyProfiler.SQLServer/EasyProfiler.SQLServer.csproj
  src/EasyProfiler.SQLServer/Extensions/Interception.cs
  src/EasyProfiler.SQLServer/Interceptors/EasyProfilerInterceptors.cs
Labels: bug
